Ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('registration.backends.default.urls')),
    path('', include('myapp.urls')),
    path('paypal/', include("paypal.standard.ipn.urls")),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    

myapp/urls.py
from django.urls import path
from myapp.views import products,detail,cart_view,return_view,cancel_view,order,grocery,review,send_email,category,contact_us,contact_us_success,faq_list
app_name='myapp'
urlpatterns = [
    path('',category,name='category'),
    path('products/<int:product_id>/<slug:slug>',products,name='products'),
    path('<int:product_id>/<slug:slug>',detail,name='detail'),
    path('cart/',cart_view, name='cart_view'),
    path('order/',order,name='order'),
    path('success/',return_view,name='return_view'),
    path('cancel/',cancel_view,name='cancel_view'),
    path('<int:product_id>/<int:pk>/review/',review,name='review'),
    path('sendmail/',send_email,name='send_email'),
    path('contact/', contact_us, name='contact_us'),  # Define the URL pattern for contact_us
    path('contact/success/', contact_us_success, name='contact_us_success'),  # Success page after submitting contact form
    path('faqs/', faq_list, name='faq_list'),
]




    

myapp/models.py
from django.db import models
from django .contrib.auth.models import User
class Category(models.Model):
    title=models.CharField(max_length=50)
    img=models.ImageField(upload_to='')
    slug=models.SlugField()
    def __str__(self):
        return self.title
class Product(models.Model):
    title=models.CharField(max_length=100)
    description=models.TextField()
    slug=models.SlugField()
    price=models.DecimalField(max_digits=10,decimal_places=2)
    img=models.ImageField(upload_to='')
    product_available=models.BooleanField(default=False)
    category = models.ForeignKey(Category,on_delete=models.CASCADE,default=1)
    def __str__(self):
        return self.title 
class Cart(models.Model):
    cart_id=models.CharField(max_length=100)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    quantity=models.IntegerField()
    timestamp=models.DateTimeField(auto_now=True)
    product=models.ForeignKey(Product,on_delete=models.PROTECT)
    def __str__(self):
        return self.product.title 
    def update_quantity(self,quantity):
        self.quantity+=quantity
        self.save()
    def total(self):
        return self.quantity*self.price
class Buy(models.Model):
    product=models.ForeignKey(Product,on_delete=models.PROTECT)
    quantity=models.IntegerField()
    price=models.DecimalField(max_digits=10,decimal_places=2)

    def __str__(self):
        return self.product.title+'_'+str(self.id)

class TimeStamp(models.Model):
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)
	user = models.ForeignKey(User,on_delete = models.CASCADE)

	class Meta:
		abstract = True

class Review(TimeStamp):
	post = models.ForeignKey(Product,on_delete = models.CASCADE)
	review = models.TextField()

	def __str__(self):
		return self.review
class ContactMessage(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=200)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def _str_(self):
        return f"Message from {self.name} - {self.subject}"

class FAQ(models.Model):
    # Your fields go here
    question = models.CharField(max_length=255)
    answer = models.TextField()

    def __str__(self):
        return self.question

myapp/forms.py
from django import forms
from .models import ContactMessage,Review  # Make sure to import your ContactMessage model


class CartForm(forms.Form):
    quantity=forms.IntegerField(initial='1')
    product_id=forms.IntegerField(widget=forms.HiddenInput)

    def __init__(self,request,*args,**Kwargs):
       self.request=request
       super(CartForm,self).__init__(*args,**Kwargs)

class ReviewForm(forms.ModelForm):
	class Meta:
		model = Review
		fields = ['review']
class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactMessage
        fields = ['name', 'email', 'subject', 'message']

myapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from myapp.models import Product,Cart,Buy,Review,Category,FAQ
from myapp.forms import CartForm,ReviewForm
from myapp.myapp import *
from django.urls import reverse
from django.shortcuts import render
from paypal.standard.forms import PayPalPaymentsForm
from django.core.mail import BadHeaderError, send_mail
from .models import ContactMessage
from .forms import ContactForm





# Create your views here.
def category(request):
    c= Category.objects.all()
    context={'c':c}
    print(c)
    return render(request,'categories.html',context) 
def products(request,product_id,slug):
    p=Product.objects.filter(category=product_id)
    if request.GET.get('q'):
        query=request.GET.get('q')
        p=Product.objects.filter(title__contains=query)
    context={'p':p}
    return render(request,'index.html',context)
  
def detail(request,product_id,slug):
    d=Product.objects.get(id=product_id)
    if request.method=="POST":
        f=CartForm(request,request.POST)
        if f.is_valid():
            request.form_data=f.cleaned_data
            add_to_cart(request)
            return redirect('myapp:cart_view')
    f=CartForm(request,initial={'product_id':product_id})
    context={'d':d,'f':f}
    return render(request,'detail.html',context)
def cart_view(request):
    if request.method=="POST" and request.POST.get('delete')=='Delete':
        item_id=request.POST.get('item_id')
        cd=Cart.objects.get(id=item_id)
        cd.delete()
    c=get_cart(request)
    t=total_(request)
    co=item_count(request)
    context={'c':c,'t':t}
    return render(request,'cart.html',context)
def order(request):
    # What you want the button to do.
    items=get_cart(request)
    for i in items:
        b=Buy(product_id=i.product_id,quantity=i.quantity,price=i.price)
        b.save()
    paypal_dict = {
        "business": "sb-w0ypz28145907@business.example.com",
        "amount": total_(request),
        "item_name": cart_id(request),
        "invoice": str(uuid.uuid4()),
        "notify_url": request.build_absolute_uri(reverse('paypal-ipn')),
        "return": request.build_absolute_uri(reverse('myapp:return_view')),
        "cancel_return": request.build_absolute_uri(reverse('myapp:cancel_view')),
        "custom": "premium_plan",  # Custom command to correlate to some function later (optional)
    }

    # Create the instance.
    form = PayPalPaymentsForm(initial=paypal_dict)
    context = {"form": form,"items":items,"total":total_(request)}
    return render(request, "order.html", context)
def return_view(request):
    return render(request,'transraction.html')
def cancel_view(request):
    return HttpResponse('Transaction Cancelled')
def grocery(request):
    return render(request,'grocery.html')
	
def review(request,product_id,pk):
    d=Product.objects.get(id=product_id)
    reviews = Review.objects.filter(post_id = product_id)
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.cleaned_data['review']
            c = Review(post_id = product_id,review = review,user = request.user)
            c.save()
            
    else:
        form = ReviewForm()

    return render(request, 'review.html', {'d':d,'form': form,'reviews':reviews})
def send_email(request):
    subject = request.POST.get("subject", "Hi Pushpa")
    message = request.POST.get("message", "OTP is 78742")
    from_email = request.POST.get("from_email", "velisilap@gmail.com")
    if subject and message and from_email:
        try:
            send_mail(subject, message, from_email, ["velisilap@gmail.com"])
        except BadHeaderError:
            return HttpResponse("Invalid header found.")
        return HttpResponseRedirect("Mail sent to Pushpa")
    else:
        # In reality we'd use a form class
        # to get proper validation errors.
        return HttpResponse("Make sure all fields are entered and valid.")


def contact_us(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            print('------------------------------------------------------------------------------------------')
            form.save()
            return redirect('myapp:contact_us_success')  # Redirect to a success page after form submission
    else:
        form = ContactForm()
    return render(request, 'contact_us.html', {'form': form})

def contact_us_success(request):
    return render(request, 'contact_us_sucess.html')

def faq_list(request):
    faqs = FAQ.objects.all()
    return render(request, 'faq_list.html', {'faqs': faqs})

myapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charsett="UTF-8">
  <meta name="viewport" content="width=device-width,
  initial-scale=1.0">
	<title>ECOMMERCE</title>
	<!-- CSS only -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

	<!-- JS, Popper.js, and jQuery -->
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/411101df7a.js" crossorigin="anonymous"></script>
	<link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-light" style="background-color: goldenrod;">
 <i><a style="background-color: goldenrod;" class="navbar-brand" href="#">ECOMMERCE</a></i>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
   <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'myapp:category' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myapp:faq_list' %}">FAQ</a>
                </li>
                
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'myapp:contact_us' %}">Contact us</a>
                </li>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#"></a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" name="q" value="{{request.GET.q}}" placeholder="{{request.user}}" aria-label="Search">
      <a href="{% url 'myapp:cart_view' %}"class="btn btn-primary"> 🛒 Cart</a>
    </form>&nbsp;
    {% if not user.is_authentication %}
    <a class="btn btn-primary" href="{% url 'auth_login' %}">Login</a>
    <a class="btn btn-primary" href="{% url 'registration_register' %}">Register</a>
    {% else %}

    <a class="btn btn-primary" href="{% url 'auth_logout' %}">Logout</a>
  </div>
  {% endif %}
</nav>
<div class="container">
	<br>
	{% block content %}
	
	{% endblock %}
</div>

</body>
</html>

myapp/templates/cart.html
{% extends 'base.html' %}
{% block content %}
<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">product</th>
        <th scope="col">price</th>
        <th scope="col">quantity</th>
        <th scope="col">Total Cost</th>

      </tr>
    </thead>
    <tbody>
    {% for i in c %}
      <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td>{{i.product}}</td>
        <td>{{i.price}}</td>
        <td>{{i.quantity}}</td>
        <td>{{i.total}}</td>
        <td>
        <form action="" method="post">
            {% csrf_token %}
            <input type="hidden" name="item_id" value="{{i.id}}">
            <input class="btn btn-danger" type="submit" name="delete" value="Delete">
        </form>
      </td>
      </tr>
      {% endfor %}
    </tbody>  
  </table><br>
  Total: ₹{{t}}<br>
  <br><br>
  <a class="btn btn-secondary" href="{% url 'myapp:order' %}">Order</a>
  &nbsp;&nbsp;&nbsp;
  
  {% endblock %}

myapp/templates/categories.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<style>
    body {
        background-color: antiquewhite;
    }
</style>
<body>
    <marquee><h1 style="color: palevioletred;">Welcome to Grocery Management System</h1></marquee>

    <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="https://i.pinimg.com/originals/b6/80/a6/b680a65ee456ba9299a356a2a0605392.jpg" alt="First slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="https://dealroup.com/wp-content/uploads/2020/05/Grocery-Offers.jpg" alt="Second slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="https://i.pinimg.com/736x/ec/50/12/ec5012ec10f64c481a4f1355fe8c20e4.jpg" alt="Third slide">
            </div>
        </div>
    </div>

    <center><h1>Products By Category</h1></center>

    <div class="row"><br>
        {% for i in c %}
            <div class="col-md-4"> <!-- Use col-md-4 for three cards in a row on medium and larger screens -->
                <div class="card">
                    <a href="{% url 'myapp:products' i.id i.slug %}"><br>
                        <img class="card-img-top" src="{{ i.img.url }}" alt="{{ i.title }}"><br>
                    </a>
                    <div class="card-body">
                        <h5 class="card-title">{{ i.title }}</h5>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</body>
</html>
{% endblock %}

myapp/templates/contact_us.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact Us</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }

        .contact-form {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            width: 300px;
        }

        .form-group {
            margin-bottom: 15px;
        }

        label {
            display: block;
            margin-bottom: 8px;
            color: #333;
        }

        input,
        button {
            width: 100%;
            padding: 10px;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
            margin-bottom: 10px;
        }

        button {
            background-color: #007bff;
            color: #fff;
            cursor: pointer;
        }

        button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>

    <div class="contact-form">
        <form>
            <div class="form-group">
                <label for="name">Name:</label>
                <input type="text" id="name" name="name" placeholder="Your Name" required>
            </div>
            <div class="form-group">
                <label for="email">Email:</label>
                <input type="email" id="email" name="email" placeholder="fake@example.com" required>
            </div>
            <div class="form-group">
                <label for="phone">Phone:</label>
                <input type="tel" id="phone" name="phone" placeholder="123-456-7890" required>
            </div>
            <button type="submit">Submit</button>
        </form>
    </div>

</body>
</html>

myapp/templates/contact_us_sucess.html
{% extends 'base.html' %}
{% block content %}
    <h3>data submitted</h3>
    {% endblock %}

myapp/templates/detail.html
{% extends 'base.html' %}
{% block content %}

<style>
    body{
        front-size: 20px;
    }
</style>
<div class="container">
<div class="row">
<div class="col-md-6">
   <h2> {{d.title}}</h2><br> 
        {{d.description}}<br><br>
       <b> ₹{{d.price}}</b><br>
</div>
        <div class="col-md-6">
       <br> <img src="{{d.img.url}}" widt="400" height="500" >
        </div>
    </div>

<form action="{% url 'myapp:detail' d.id d.slug%}" method="post">
    {% csrf_token %}
    {{ f }}
    <input type="submit" value="Add to Cart">
</form><br><br>
<a class="btn btn-primary" href="{% url 'myapp:review' d.id d.pk %}"><button>Can you please give Review</button></a>
{% endblock %}

myapp/templates/faq_list.html
[9:23 am, 08/12/2023] Bhavya: <!-- myapp/templates/myapp/faq_list.html -->
<!DOCTYPE html>
<html>
<head>
    <title>FAQ List</title>
</head>
<body>
    <h1>Frequently Asked Questions</h1>
    <ul>
            <li>
                <strong>{{ faq.question }}</strong><br>
                {{ faq.answer }}
            </li>
    </ul>
</body>
</html>

myapp/templates/index.html
{% extends 'base.html' %}
{% block content %}
<marquee><h1 style="color: palevioletred;">Grocery Products</h1></marquee>
<div class="container">
  <div class="row">
    <div class="row">
      {% for i in p %}
      <div class="col-md-6 md-4"><br>
        <div class="card">
              <img src="{{i.img.url}}" width="300" height="300"><br>
              <div class="card-body">
                {% if i.product_available is True %}
                <h5 class="card-title"><a href="{% url 'myapp:detail' i.id i.slug %}"><b>{{i.title}}</b></a><br></h5>
                ⟨₹⟩{{i.price}}
                <br><br><br>
                {% else %}   
                <b>Out Of Stock</b>
                {% endif %}
              </div>
            </div> 
          </div>
  
      {% endfor %} <br><br> 
        </div>


  </div>
  
  {% endblock %}

myapp/templates/order.html
{% extends 'base.html' %}
{% block content %}
<b>Cart</b><br>
{% for i in items %}
{{i.product}}<br>
{% endfor %}
Pay: {{total}}
<h1>Show me the money!</h1>
<!-- writes out the form tag automatically -->
{{ form.render }}
{% endblock %}

myapp/templates/review.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-6">
        <b>{{ d.title }}</b><br>
        {{ d.description }}<br>
        {{ d.price }}<br>
    </div>
    <div class="col-md-6">
        <img src="{{ d.img.url }}" width="400" height="500">
    </div>
</div>

<style>
        body{
          background-color:lightcyan;

        }
    .my-form {
        max-width: 400px; /* Adjust the maximum width as needed */
    
    }

    .my-form form {
        padding: 20px;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    .my-form .form-group {
        margin-bottom: 15px;
    }

    .my-form button {
        background-color: #007bff;
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 3px;
        cursor: pointer;
    }

    .my-form button:hover {
        background-color: #0056b3;
    }
</style>

<div class="my-form">
    <form action="" method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ form.as_p }}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

<div class="mt-4">
    <h6>Reviews:</h6>
    {% for review in reviews %}
        {{ forloop.counter }} - {{ review.review }} <br>
        at {{ review.created_at }} by {{ review.user }} <br>
    {% endfor %}
</div>
{% endblock %}

myapp/templates/transraction.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center><br><br><br><br>
    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7fLGbTFZKIDyOeXJFQ3C16nwyt-qlL4iKyA&usqp=CAU" width="70" height="70">
    <h1>Order Placed</h1>
    </center>
</body>
</html>